### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by ShalokShalom** [marcelobarreto/supabase-rb#4]
Seems like the Readme still waits for its listings of use cases. 

Is there *any* form of documentation coming up?

**Comment by plusjade** [comment]
This repo contains zero functionality; Supabase should make that clear upfront. There's likely no strong reason for a ruby client because Supabase gives full host url and credentials to the database. Connect there and use ActiveRecord.

FWIW I spent a few hours using [Faraday](https://github.com/lostisland/faraday) to verify I can make HTTP calls to Supabase just like clients. It works but I quickly realized I'd be reimplementing operations based on Supabase's custom URL parameter language vs just running SQL.

Do others have reasons for going though the HTTP API via Ruby?

**Comment by ShalokShalom** [comment]
I dont use this, do you want to keep this thread open anyway?
